# Używamy oficjalnego obrazu Node.js jako bazy (Kuchnia)
FROM mcr.microsoft.com/devcontainers/javascript-node:20-bookworm

# [OPCJONALNIE] Tu będziemy dodawać globalne narzędzia, jeśli będą potrzebne offline
# Na razie trzymamy standard, by obraz był lekki i stabilny.